# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EasyJobs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EasyJobs
    pod 'Firebase/Core'
    pod 'FirebaseUI/Auth'
    pod 'Firebase/Analytics'	
    pod 'Firebase/Firestore'
    pod 'Alamofire', '~> 5.0.0-rc.3'
    pod 'SwiftyJSON', '~> 4.0'		
	
  target 'EasyJobsTests' do
    inherit! :search_paths
    # Pods for testing
      pod 'Firebase/Core'
      pod 'FirebaseUI/Auth'
      pod 'Firebase/Analytics'
      pod 'Firebase/Firestore'
      pod 'Alamofire', '~> 5.0.0-rc.3'	
      pod 'SwiftyJSON', '~> 4.0'
  end

  target 'EasyJobsUITests' do
    inherit! :search_paths
    # Pods for testing
      pod 'Firebase/Core'
      pod 'FirebaseUI/Auth'	
      pod 'Firebase/Analytics'
      pod 'Firebase/Firestore'
      pod 'Alamofire', '~> 5.0.0-rc.3'
      pod 'SwiftyJSON', '~> 4.0'
  end

end
